#!/bin/bash
set -euo pipefail

# this script can be used to start a container with the libdragon-workspace image
# and run a command, removing the container when it exits.

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

# - start a docker container from the libdragon-workspace image
# - run as the current host os user, to avoid permission issues
# - mount the current directory to /workspace in the container
# - change the working directory to /workspace
# - and run the command passed as arguments
docker run \
    --volume "$SCRIPT_DIR:/workspace" \
    --workdir /workspace \
    libdragon-workspace "$@"
